server:
  maxThreads: 512
  applicationContextPath: /todoist-demo-dropwizard
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  loggers:
    com.demo: INFO

mongoDBConnection:
  credentials:
    username: "user_todos"
    password: "pAsw0Rd123"
  seeds:
    - host: "mongodb"
      port: 27017
  database: "todos"

swagger:
  basePath: /todoist-demo-dropwizard
  resourcePackage: com.demo.resources
  scan: true
  info:
    version: "1.0.0"
    title: "Todoist API CRUD"
    description: "A simple API used for Todos' and its corresponding tasks' CRUD operatios on MongoDB collection"
    termsOfService: "http://swagger.io/terms/"
    contact:
      name: "Todoist API "
    license:
      name: "Adil Hussain"
